# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  orderingdb:
    image: postgres
  messagebroker:
    image: rabbitmq:management

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: Services/BasketAPI/Dockerfile
  discountgrpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Dockerfile
  orderingapi:
    image: orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/OrderingAPI/Dockerfile
  yarpapigateway:
    image: yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
volumes:
  postgres_catalog:
  postgres_basket:
  postgres_ordering:
